name: Conditional workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment"
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  run-conditional-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Show chosen environment
        run: echo "Environment chosen:${{ github.event.inputs.environment }}"

      - name: Deploy to production
        if: ${{ github.event.inputs.environment == 'production' }}
        run: echo "Deploying to production!"

      - name: Test mode
        if: ${{ github.event.inputs.environment == 'development' || github.event.inputs.environment == 'staging' }}
        run: echo "Running in test mode"
