name: dependencies example
on:
  workflow_dispatch:

jobs:
  npmFramework:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-report
        path: tests-report.xml
    - run: npm install 
    - run: npm test
    - name: verification
      run: ls -alhR
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-report
        path: tests-report.xml
    - name: Bundle application into ZIP
      run: zip -r app-bundle.zip ./*
